config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get 'about' => 'welcome#about'

  get 'downgrade' => 'charges#downgrade'

  resources :users, only: [:show]

  resources :wikis

  resources :charges, only: [:new, :create, :destroy]

  resources :wikis, only: [] do

     resources :collaborators, only: [:new, :create, :destroy]
   end


  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/collaborator.rb
class Collaborator < ApplicationRecord
  belongs_to :user
  belongs_to :wiki
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController

  before_action :check_if_already_collaborator, only: [:create]
  before_action :check_if_user_exists, only: [:create]
  before_action :check_if_private_wiki, only: [:new]

  def new
    @wiki = Wiki.find(params[:wiki_id])
    @collaborator = Collaborator.new
  end

  def create

    wiki = Wiki.find(params[:wiki_id])
    user = User.where(email: params[:collaborator][:user]).first
    collaborator = user.collaborators.build(wiki: wiki)

    if collaborator.save
     flash[:notice] = "Collaborator added."
    else
     flash[:alert] = "Failed."
    end


    redirect_to wiki
  end

  def destroy
     wiki = Wiki.find(params[:wiki_id])
     collaborator = Collaborator.find(params[:id])


     if collaborator.destroy
       flash[:notice] = "Collaborator deleted"
     else
       flash[:alert] = "Failed."
     end
       redirect_to wikis_path
   end

  private
  def check_if_user_exists
    collaborator = Collaborator.new
    wiki = Wiki.find(params[:wiki_id])
    user = User.where(email: params[:collaborator][:user]).first

    if !user
      flash[:alert] = "That email does not belong to a blocipedia user"
      redirect_to wiki
    end
  end

  def check_if_already_collaborator
    collaborator = Collaborator.new
    wiki = Wiki.find(params[:wiki_id])
    user = User.where(email: params[:collaborator][:user]).first

    if Collaborator.where(user: user, wiki: wiki).count > 0
      flash[:alert] = "User is already a collaborator"
      redirect_to wiki
    end
  end

  def check_if_private_wiki
    wiki = Wiki.find(params[:wiki_id])
    if !wiki.private
      flash[:alert] = "No need to add collaborators to a public wiki"
      redirect_to wiki
    end
  end

end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/views/collaborators/_collaborator.html.erb
<% if collaborator = current_user.collaborator_for(wiki) %>

   <%= link_to [wiki, collaborator], class: 'btn btn-danger', method: :delete do %>
     <i class="glyphicon glyphicon-star-empty"> </i>&nbsp; Stop collaborating on this wiki
   <% end %>
<% end %>
<% if wiki.user == current_user %>
   <%= link_to new_wiki_collaborator_path(wiki.id), class: 'btn btn-primary' do %>
     <i class="glyphicon glyphicon-star"> </i>&nbsp; Add Collaborator
   <% end %>

<% end %>

app/views/collaborators/new.html.erb
<h1>Select a collaborator</h1>

<div class="row">
  <div class="col-md-8">
    <%= form_for [@wiki, @collaborator] do |f| %>
      <div class="form-group">

        <%= f.label :user %>
        <%= f.text_field :user, class: 'form-control', placeholder: 'Enter email of collaborator' %>

          <!-- <%= f.collection_select(:user, User.all, :id, :email) %> -->

     </div>
     <div class="form-group">
       <%= f.submit "Save" %>
     </div>
    <% end %>
  </div>

</div>