config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get 'about' => 'welcome#about'

  get 'downgrade' => 'charges#downgrade'

  resources :users, only: [:show]

  resources :wikis

  resources :charges, only: [:new, :create, :destroy]

  resources :wikis, only: [] do

     resources :collaborators, only: [:new, :create, :destroy]
   end


  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<br>
 <div class="jumbotron">
   <h1>Blocipedia: Social, Markdown Wikis</h1>
   <p>Create and share Markdown Wikis</p>
   <p>
     <!--fix this route path after user func is created-->
     <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %>
     Or
     <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %>
   </p>
 </div>

 <div class="row">
   <div class="col-md-4">
     <h3>Create as many public wikis as you want with Free Plan!</h3>

   </div>
   <div class="col-md-4">
     <h3>Create Private Wikis with Premium Plan!</h3>
     <!--update this link -->
     <% if current_user %>
       <% if current_user.standard? %>
        <%= link_to "Upgrade to Premium Plan", new_charge_path, class: 'btn btn-primary' %>
       <% elsif current_user.premium? %>
        <%= link_to "Downgrade to Free", downgrade_path, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to downgrade? All your private wikis will become public. Seems stupid, you have aready paid?'} %>
       <% else %>
         <h3>You are an admin</h3>
       <%end%>
    <%end%>

   </div>
 </div>