config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get 'about' => 'welcome#about'

  get 'downgrade' => 'charges#downgrade'

  resources :users, only: [:show]

  resources :wikis

  resources :charges, only: [:new, :create, :destroy]

  resources :wikis, only: [] do

     resources :collaborators, only: [:new, :create, :destroy]
   end


  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user
  has_many :collaborators, dependent: :destroy
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  before_action :authorize_private, only: [:create, :update]


  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
    @collaborators = User.joins(:collaborators).where(collaborators: { wiki: @wiki })
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  def create
    @wiki = Wiki.new
    authorize @wiki
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]
    @wiki.user = current_user

    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new

    end

  end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def update
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]

    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again later."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    if @wiki.destroy
      flash[:notice] = "Wiki was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :wiki
    end
  end

  private
  def authorize_private
    wiki = Wiki.find(params[:id])
    wiki.title = params[:wiki][:title]
    wiki.body = params[:wiki][:body]
    wiki.private = params[:wiki][:private]
    wiki.user = current_user
    if wiki.private && wiki.user.standard? && Collaborator.where(user: wiki.user, wiki: wiki).count == 0
      flash[:alert] = "You do not have permission to create private Wikis. Please upgrade to Premium!"
      redirect_to wikis_path
    end
  end


end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

 <div class="row">
   <div class="col-md-8">
     <%= form_for @wiki do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
       </div>
       <div class="form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
       </div>
       <% if @wiki.private %>
        <small>This Wiki is Private</small>
       <%else%>
        <small>This Wiki is Public</small>
       <%end%>
       <div class="form-group">
         <%= f.label :private, class: 'checkbox' do %>
          Private <%= f.check_box :private, :style => "margin-left: 10px;"  %>
         <% end %>
       </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>
<% if user_signed_in? %>
  <p>Here you can see all public Wikis, and all your private Wikis</p>
<% else %>
  <p>All public Wikis.</p>
<% end %>
 <% @wikis.each do |wiki| %>
   <div class="media">
     <div class="media-body">
       <h4 class="media-heading">
         <%= link_to markdown(wiki.title), wiki %>
       </h4>
     </div>
   </div>
 <% end %>
  <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<div class="row">
  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
      <div class="form-group">
       <%= f.label :title %>
       <%= f.text_field :title, class: 'form-control', placeholder: 'Enter wiki title' %>
     </div>
     <div class="form-group">
       <%= f.label :body %>
       <%= f.text_area :body, rows: 20, class: 'form-control', placeholder: 'Enter wiki body' %>
     </div>
     <div class="form-group">
       <%= f.label :private, class: 'checkbox' do %>
        Private <%= f.check_box :private,  :style => "margin-left: 10px;"  %>
       <% end %>
     </div>
     <div class="form-group">
       <%= f.submit "Save" %>
     </div>
    <% end %>
  </div>

</div>

app/views/wikis/show.html.erb
<h1><%= markdown(@wiki.title) %></h1>

 <div class="row">
   <div class="col-md-8">
     <p><%= markdown(@wiki.body) %></p>
     <% if @wiki.private %>
      <small>This Wiki is Private</small>
     <%else%>
      <small>This Wiki is Public</small>
     <%end%>
   </div>
 </div>
   <div class="col-md-4">
 <!-- #5 -->
     <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
     <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete the Wiki?'} %>
   </div>

   <div class="row">
     <% if current_user && @wiki.private %>
         <%= render partial: 'collaborators/collaborator', locals: { wiki: @wiki } %>
       <% end %>
   </div>
   <div class="row">
   <% if @wiki.user == current_user %>
     <div class="col-md-4">
       <% @collaborators.each do |collaborator| %>
       <h1>Remove Collaborators</h1>

        <%= link_to [@wiki, collaborator.collaborator_for(@wiki)], class: 'btn btn-danger', method: :delete do %>
          <i class="glyphicon glyphicon-star-empty"> </i>&nbsp; <%= collaborator.email%>
        <% end %>
       <% end %>

     </div>
  <% end %>
</div>